name: haskell-template
version: 0.0.1.0
license: MIT
author: "Alexander Kobjolke"
maintainer: "alex@jakalx.net"
copyright: "Alexander Kobjolke 2022"

extra-source-files:
  - README.org

dependencies:
  - base >= 4.11 && < 5

ghc-options:
  - -Wall
  - -Wunused-packages

library:
  source-dirs: src

executables:
  hello:
    source-dirs: app
    main: hello.hs
    dependencies:
      - haskell-template
